// sub1-react-sub-vue3/src/index.ts
import { vueBridge } from '@garfish/bridge-vue-v3';
import { createApp } from 'vue';
import { createRouter, createWebHistory } from 'vue-router';
import About from './About.vue';
import App from './App.vue';
import Home from './Home.vue';
import './index.css';
import Router from './Router.vue';

const routes = [
  { path: '/', component: Router },
  { path: '/home', component: Home },
  { path: '/about', component: About },
];

function newRouter(basename: string) {
  console.log('11111 basename', basename);
  return createRouter({
    history: createWebHistory(basename),
    routes,
  });
}

export const provider = vueBridge({
  rootComponent: App,
  // 可选，注册 vue-router或状态管理对象
  handleInstance: (vueInstance, { basename }) => {
    vueInstance.use(newRouter(basename));
  },
});
console.log(window.__GARFISH__);

if (!window.__GARFISH__) {
  const app = createApp(App);
  app.use(newRouter('/'));
  app.mount('#sub-vue3-root');
}

// sub1-react/src/index.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import { RootComponent } from './App';

import { reactBridge } from '@garfish/bridge-react-v18';

export const provider = reactBridge({
  el: '#root',
  rootComponent: RootComponent,
});

console.log(window.__GARFISH__);

const rootEl = document.getElementById('sub1-react-mount-id');
if (rootEl) {
  const root = ReactDOM.createRoot(rootEl);
  root.render(
    <React.StrictMode>
      <RootComponent />
    </React.StrictMode>,
  );
}
